### ISSUE TITLE
2 controllers when connected to usb 

### ISSUE THREAD

**Issue by gomisensei** [chrippa/ds4drv#101]
when i plug controller into usb, it connects via bluetooth, which creates 2 devices, js0, and js1, only one of which works, which screws up my controller configs.  Is there a way for ds4drv to overwrite , i.e. only have one device connected at a time?

**Comment by Enigma0** [comment]
This might be the issue with https://github.com/chrippa/ds4drv/issues/97 also ?

**Comment by Ape** [comment]
Is this #45?

**Comment by Enigma0** [comment]
@Ape Could be

**Comment by gomisensei** [comment]
@ape Yep, think it is, or close enough., Should I close?
