### ISSUE TITLE
Using ds4drv as a python library instead of service?

### ISSUE THREAD

**Issue by zacwitte** [chrippa/ds4drv#108]
Is it possible to use ds4drv as a python package that's imported, creating the BluetoothBackend, and devices in my own code to get greater control rather than using it as a service that created a uinput device? 

I'm trying to get access to controller connect and disconnect events and avoid the extra device that hidraw driver creates. I'd also like to programatically access the battery level and set the LED color, which I don't think is possible through evdev.

**Comment by Ape** [comment]
Yes, this is possible, but ds4drv doesn't support this feature. You will have to modify the code.
