### ISSUE TITLE
Is there a passthrough to PS4?

### ISSUE THREAD

**Issue by AlexanderReichl** [chrippa/ds4drv#137]
Hi, I'd like to connect the DS Controller to my raspberry and grab the input data and I'd like to still transfer the controller data to the PS4 system. Is that anyhow possible?

As soon as I connt via ds4drv PS4 loses connection to that controller.

Thanks and kind regards
Alex

**Comment by Ape** [comment]
Interesting idea. This should be possible with the right hardware, but this is out of scope for ds4drv.
