### ISSUE TITLE
Wi-fi network disconnects whenever DS4 is connected

### ISSUE THREAD

**Issue by Chris-Harries** [chrippa/ds4drv#138]
I'm using ds4drv with Linux Mint and I have an odd issue. Whenever I connect my DS4 using ds4drv, my wi-fi network disconnects. It reconnects again when I stop the process. When I connect my DS4 directly without using ds4drv. This problem also occurs when I connect my DS4 directly then load up ds4drv using Hidraw mode.

**Comment by Ape** [comment]
I'm closing this since this is most likely not an issue in ds4drv. You can still use the issue for discussion.

Sounds like your bluetooth hardware cannot be used at the same time with your wifi. You might want to try to use an external usb bluetooth device.
