### ISSUE TITLE
[Feature Request]  maintain virtual /js* device when switching profiles

### ISSUE THREAD

**Issue by benmoran56** [chrippa/ds4drv#33]
Current functionality: 
When using the "emulate-xpad" option in the [Controller:1] section, ds4drv will create a virtual /dev/input/js\* device. When switching to the [Keyboard] profile, however, this virtual device dissapears. It will re-appear when switching back, as expected. 

Feature request: 
It would be nice to keep this virtual js device, even when switching to a keyboard/mouse profile. This is because in some games, they lose joystick control if the joystick device dissapears temporarily. (These are often the same games that do not support "hot-pluggin" of joysticks). For this reason, it's impossible to switch over to the keyboard profile for a moment and then switch back.  I think it would be helpful if the virtual js device would remain in these cases. 

Thanks for all your work on this!

**Comment by Ape** [comment]
@benmoran56 Has this issue been solved?

**Comment by benmoran56** [comment]
No, it hasen't. The repository hasen't been touch for 2 years, so I closed my ticket. Someone posted a way to do this in another thread, but it didn't get anywhere due to chrippa's dissapearance. 

You seem fairly active with this project, and if I remember your previous rumble fork. Do you think you can take over the project and start merging some of the fixes and open pull requests on your branch? It's such a shame that the project is stagnating like this. I'd be happy to contribute there, but I don't have the time to maintain it myself at the moment.

**Comment by Ape** [comment]
I'm afraid I don't have the time for this project right now. It would be great if the project was more active again. Please leave the issues and pull requests open if they are not solved. Perhaps somebody will maintain this project better in the future.

**Comment by benmoran56** [comment]
I understand. I hope someone else can step up and take over, or possibly @chrippa will come back at some point to continue maintenance. There are already several pull requests, so obviously there is interest.
