### ISSUE TITLE
Feature Request: Option to disable LED entirely

### ISSUE THREAD

**Issue by ntzrmtthihu777** [chrippa/ds4drv#37]
yeah, I personally have no use for the led on board, so I'd like to be able to just 'turn it off' entirely to conserve battery. 

Btw, many thanks for setting this up; I'm liking the ds4 <=> linux interaction much better than the ds3 and the horrid setup of sixad and qtsixa; the trackpad is a pretty nice plus too.

**Comment by Ape** [comment]
It is not possible to set the LED in hidraw mode. Please open an issue or a pull request if you have concrete ideas about how to add the feature.
