### ISSUE TITLE
No connection in hidraw mode

### ISSUE THREAD

**Issue by athanase** [chrippa/ds4drv#38]
Hi,
I use ubuntu 14.04 with bluez 5.18 and bluetooth 2.0 and bluetooth 2.1 adapters to test your program. I work really well in normal mode, but nothing happens in hidraw mode, any ideas ?
PS: Note that when I pair the remote in Ubuntu using the bluetooth manager, the remote gets disconnected shortly after the pairing, I don't know if this is normal.

Here is the normal output:

```
[info][controller 1] Created devices /dev/input/js0 (joystick) /dev/input/event16 (evdev) 
[info][bluetooth] Scanning for devices
[info][bluetooth] Found device A4:15:66:88:5E:9A
[info][controller 1] Connected to Bluetooth Controller (A4:15:66:88:5E:9A)
[info][bluetooth] Scanning for devices
[info][controller 1] Battery: Fully charged
```

Hidraw mode:

```
[info][controller 1] Created devices /dev/input/js0 (joystick) /dev/input/event16 (evdev) 
[info][hidraw] Scanning for devices
```

**Comment by Ape** [comment]
This issue sometimes happens to me. First make sure that `bluetooth.service` is running. You can also try these command on `bluetoothctl`:

```
scan on
remove xx:xx:xx:xx:xx:xx (try to remove the misbehaving old pairing)
trust xx:xx:xx:xx:xx:xx
pair xx:xx:xx:xx:xx:xx
scan off (turning off scanning may help, or it might just be for the worse)
connect xx:xx:xx:xx:xx:xx (you can try to manually connect the controller after pairing)
```
where `xx:xx:xx:xx:xx:xx` is the MAC address of your controller. For each step you can try to put your controller to the pairing mode (hold PS+SHARE) or the normal mode (tap PS).
