### ISSUE TITLE
Can't pair more than 2 controllers with GBU421

### ISSUE THREAD

**Issue by keberos** [chrippa/ds4drv#44]
New problem with the iogear gbu421. I can't do more than 2 controllers. See error below.

desktop@steamos:~/Downloads/ds4drv/ds4drv$ sudo ds4drv
[info][controller 1] Created devices /dev/input/js0 (joystick) /dev/input/event4 (evdev)
[info][bluetooth] Scanning for devices
[info][bluetooth] Found device A4:15:66:67:59:D3
[info][controller 1] Connected to Bluetooth Controller (A4:15:66:67:59:D3)
[info][bluetooth] Scanning for devices
[info][controller 1] Battery: 62%
[info][bluetooth] Found device A4:15:66:DC:08:91
[info][controller 2] Created devices /dev/input/js1 (joystick) /dev/input/event16 (evdev)
[info][controller 2] Connected to Bluetooth Controller (A4:15:66:DC:08:91)
[info][bluetooth] Scanning for devices
[info][controller 2] Battery: 75%
[info][bluetooth] Found device A4:15:66:67:57:92
[error][bluetooth] Unable to connect to detected device: Failed to set operational mode: [Errno 107] Transport endpoint is not connected
[info][bluetooth] Scanning for devices
[error][bluetooth] Error while scanning for devices: 'hcitool scan' returned error. Make sure your bluetooth device is powered up with 'hciconfig hciX up'.
desktop@steamos:~/Downloads/ds4drv/ds4drv$

**Comment by Ape** [comment]
Does this still happen on ds4drv 0.5.1?

**Comment by geokhentix** [comment]
It does not. I have a GBU421 with a Pi3, and I'm able to pair up two DS4's. Hidraw however does not work for me. No errors are reported, but the controller doesn't pair, nor does ds4drv report any kind of activity.

**Comment by Ape** [comment]
ds4drv cannot pair hidraw controllers. You have to pair it with other tools like bluetoothctl. When it is paired and connected ds4drv will see it in hidraw mode.

Closing this as reported fixed.
