### ISSUE TITLE
Specifying 2 profiles in .conf file actually creates 3

### ISSUE THREAD

**Issue by Susurrus** [chrippa/ds4drv#48]
If I use the example .conf file and enable profile switching, I see that it toggles through an xpad, kbmouse, and default profile. I never created the default one, and the profile switching has only been specified for xpad and the kbmouse one with a `profiles = xpad,kbmouse`.

**Comment by Ape** [comment]
This is expected. If you have concrete ideas about how to improve documentation please open an issue or a pull request.
