### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Okamooki** [chrippa/ds4drv#55]
Installation fails with this error:

Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-jK6NYC/evdev/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-o3VBQV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-jK6NYC/evdev

It seems like it might be a compiler error but i don't know how to proceed

**Comment by Ape** [comment]
Which Python version? Which OS? What command did you run?

**Comment by Okamooki** [comment]
os is ubuntu 14.04,
i do not know how to check what python version pip uses

**Comment by Ape** [comment]
Does this still occur?

**Comment by dotWAVE** [comment]
I have this same issue trying to sudo pip install ds4drv, running opensuse tumbleweed 20170703. 
pip is version 9.0.1 on python 3.6.

**Comment by Ape** [comment]
I'm closing this. For anybody else who might have this issue in the future, try installing python-devel package (or equivalent on your distro).
