### ISSUE TITLE
Lightbar Colors

### ISSUE THREAD

**Issue by Alkaris** [chrippa/ds4drv#60]
I decided to test out what colors worked and what colors didn't when I changed them with `ds4drv` and these are what worked for me since it's all HEX Codes, not every color shows up well as the LED seems to be limited to a set number of colors.

```
LED Color Profiles:

 Lightbar OFF  = 000000

 Blue (def.)   = 0000ff / 000fff / 110196 / 070496
 Red           = ff0000 / ff0f0f / 340000 / 990000
 Yellow        = fff000 / ffff00 / f0ff0f / f0ff00 / 678901
 White         = fffff0 / ffffff / fff0ff / f0ffff / f0f0f0
 Pink          = ff00ff / ff0fff / ff00c1 / fd00ff / 330033
 Grey ?        = 0f0f0f
 Green         = 00ff00 / 199600 / 006300 / 00cc00 / 66cc00
 Teal          = 1fca1f / 008080
 Light Blue    = 123456 / 112233 / 4682b4 / 66cccc
 Peach         = 8b4513 / 993333 / cc6633 / ff3333 / cc821a
 Purple        = 660033 / 990066 / 990099
 Orange        = 663300 / 993300 / cc3300 / ff3300
```

there isn't much color variation differences in these HEX Codes, but they all seem to produce the colors I've listed. A lot of the colors I tested would appear on the LED as white or a really light color that still looked white even if it were another color say like **Light-Blue** or **Light-Green** or **Light-Yellow**.

**Comment by Ape** [comment]
Thanks for the information, but I'll close this as it is not an issue or a feature request. You can add the information to wiki.
