### ISSUE TITLE
Still relevant?

### ISSUE THREAD

**Issue by ntzrmtthihu777** [chrippa/ds4drv#62]
With the hid-sony kernel module adding better support for this device into the kernel itself, is this still relevant for normal usage, eg none of the profiles and xpad and such?

**Comment by sasann** [comment]
I only use it to get my controller battery percentage. Any way I can do it without ds4drv?

**Comment by benmoran56** [comment]
Yes, battery usage shows up under /sys/class/power_supply/..../capacity. For example, the battery power for my trackpad can be found at: 
/sys/class/power_supply/hid-28\:37\:37\:2e\:07\:82-battery/capacity

**Comment by sasann** [comment]
@benmoran56 Awesome tip. Thanks.

**Comment by samdraz** [comment]
better useful if this exit as library to other programs

**Comment by TamasBarta** [comment]
I have 4.3.3 kernel, and I cannot get my controller to work over bluetooth without ds4drv. I might miss something, but this really makes ds4drv still relevant.

**Comment by Ape** [comment]
The plug-and-play kernel driver should work nicely, but ds4drv still have many advanced features compared to it. There are two ways to use ds4drv:

- Raw bluetooth mode (default) provides an alternative way to use the controller. This may be useful in case the kernel driver doesn't work or has some issues.
- Hidraw mode (`--hidraw`) uses the kernel driver and automatically gets all its features. In addition, ds4drv also adds its features like profiles and advances keymappings.
