### ISSUE TITLE
Failed to create input 

### ISSUE THREAD

**Issue by hjsav** [chrippa/ds4drv#69]
every time I install i can't get it to install. This is what i get when I run the command.   

$ ds4drv
[error][controller 1] Failed to create input device: "/dev/uinput" cannot be opened for writing
[info][bluetooth] Scanning for devices

please help and thank you.

**Comment by MrPepperoni** [comment]
Probably ds4drv doesn't have permissions to access /dev/uinput, please check https://github.com/chrippa/ds4drv#permissions
You can also try using --hidraw if you have bluez 5.14+, I found https://wiki.gentoo.org/wiki/Sony_DualShock#DualShock_4 to be the most straightforward way to pair the controller.

**Comment by Ape** [comment]
Is this still an issue?

**Comment by CoryParsnipson** [comment]
I had the same problem, and I found [this page](https://groups.google.com/forum/#!topic/ds4drv/CdPZm4EZRMM) that has the answer, I think.

I did not have uinput loaded by default. That is at the time, lsmod | grep uinput returns nothing. If I load uinput ds4drv seems to be able to create /dev/input/js* just fine.

To make uinput start at boot, you can add a file, /etc/modules-load.d/uinput.conf, for example with these contents:

`/etc/modules-load.d/uinput.conf
--------------------------------------------------
# Load uinput module at boot
uinput`

As Joseph says in the thread I linked.

**Comment by Ape** [comment]
Thanks for the solution. This is not really a bug in ds4drv so I am closing this. Please submit a pull request if you have ideas about how to improve the documentation or error printing.

**Comment by CoryParsnipson** [comment]
Ok, thanks. I'll probably see if I can add a little section about uinput underneath the udev rules thing.
